spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: notification-service


#    spring:
#      mail:
#        host: smtp.gmail.com
#        port: 587
#        username: nedrabenyoussef9@gmail.com
#        password: Nzbenyoussef.123
#        properties:
#          mail:
#            smtp:
#              auth: true
#              starttls:
#                enable: true
#              ssl:
#                trust: smtp.gmail.com
#
