spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: customer-service

  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: "http://localhost:9090/realms/project-management-micro-service"